@echo off
echo Starting SkillSync Development Environment...

echo Starting Infrastructure (Postgres/Redis)...
start cmd /k "docker compose up postgres redis"

echo Starting FastAPI AI Service...
start cmd /k "docker compose up ai-service --build"

echo Starting Spring Boot Backend...
start cmd /k "cd apps\backend\skillfuze && .\mvnw.cmd spring-boot:run"

echo Starting Next.js Frontend...
start cmd /k "cd apps\web && pnpm dev"

echo All services are booting up!
